version: 2.0
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            apt-get update && apt-get -y --no-install-recommends install rabbitmq-server
            service rabbitmq-server start
            python setup.py test
