version: 2.0
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Run Tests
          command: |
            apt-get update && apt-get -y --no-install-recommends install rabbitmq-server
            service rabbitmq-server start
            python setup.py test
