version: 2.0
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            apt-get update && apt-get -y --no-install-recommends install rabbitmq-server
            pip install 'pytest~=6.2' 'pytest-cov~=2.7' 'mock~=2.0' 'pika>=0.13' 'redis>=3.4'
            pip install -e .
            pytest
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "30 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
