version: 2.0
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Run Tests
          command: |
            python setup.py test

